BEGIN;

DELETE FROM processing_policy_config
WHERE policy_key IN (
    'COLLECTION_AUTOMATION_ENABLED',
    'COLLECTION_AUTOMATION_INTERVAL_HOURS',
    'COLLECTION_AUTOMATION_RETRY_HOURS',
    'COLLECTION_AUTOMATION_BATCH_SIZE',
    'COLLECTION_AUTOMATION_REVIEW_RECOVERY_LIMIT',
    'COLLECTION_AUTOMATION_STALE_RUN_HOURS'
);

INSERT INTO migration_history (migration_name)
VALUES ('0044_remove_admin_collection_scheduler.sql')
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
