"""Versioned acquisition contract shared by health and the collection runner."""
COLLECTION_PROCESS_VERSION = "2026-10-08-owned-source-identity-proof-v9"
MAX_RESEARCH_ROUNDS = 2
MAX_ADDITIONAL_PER_DETAIL = 2
MAX_ADDITIONAL_PER_RUN = 48
MAX_PLANNER_CALLS_PER_RUN = 8
MAX_LINKS_PER_DETAIL = 48

MAX_RENDERS_PER_DETAIL = 1
MAX_RENDERS_PER_RUN = 48
MAX_REPARSES_PER_SNAPSHOT_VERSION = 1
