const COPY = {
  "en": {
    "title": "Your comparison",
    "view": "View comparison",
    "add": "Add to comparison",
    "selected": "Added to comparison",
    "otherBanks": "Same type at other banks",
    "share": "Copy link",
    "copied": "Link copied",
    "copyFailed": "Copy this link",
    "save": "Save on this device",
    "saved": "Saved on this device",
    "openSaved": "Open saved comparison",
    "deleteSaved": "Delete saved comparison",
    "deleted": "Saved comparison deleted",
    "local": "Saved only on this device until you delete it.",
    "storageError": "Device storage is unavailable. You can still copy a link.",
    "changed": "Conditions changed",
    "missing": "No longer available",
    "error": "Could not check this product",
    "loading": "Checking latest conditions…",
    "retry": "Try again",
    "empty": "Choose up to four products to compare.",
    "browse": "Browse products",
    "clear": "Clear",
    "remove": "Remove",
    "count": "{count} selected",
    "mixed": "Different types or currencies. Compare individual facts only; a combined calculation is unavailable.",
    "conditions": "Rate basis or terms differ or are unconfirmed. A like-for-like rate comparison and calculation are unavailable.",
    "invalid": "This comparison link is invalid. Choose up to four products.",
    "currency": "Currency",
    "refresh": "Check latest",
    "limit": "Up to four products."
  },
  "ko": {
    "title": "비교 목록",
    "view": "비교 보기",
    "add": "비교에 추가",
    "selected": "비교에 추가됨",
    "otherBanks": "다른 은행의 같은 유형 비교",
    "share": "링크 복사",
    "copied": "링크 복사됨",
    "copyFailed": "이 링크를 복사하세요",
    "save": "이 기기에 저장",
    "saved": "이 기기에 저장됨",
    "openSaved": "저장한 비교 열기",
    "deleteSaved": "저장한 비교 삭제",
    "deleted": "저장한 비교를 삭제했습니다",
    "local": "삭제할 때까지 이 기기에만 저장됩니다.",
    "storageError": "기기 저장을 사용할 수 없습니다. 링크를 복사해 보관하세요.",
    "changed": "조건 변경됨",
    "missing": "더 이상 제공되지 않음",
    "error": "상품을 확인하지 못했습니다",
    "loading": "최신 조건 확인 중…",
    "retry": "다시 시도",
    "empty": "비교할 상품을 최대 4개 선택하세요.",
    "browse": "상품 둘러보기",
    "clear": "초기화",
    "remove": "제외",
    "count": "선택 {count}개",
    "mixed": "유형 또는 통화가 다릅니다. 개별 조건만 비교할 수 있으며 통합 계산은 불가합니다.",
    "conditions": "금리 기준·만기가 다르거나 미확인 상태입니다. 동일 조건의 금리 비교와 계산은 불가합니다.",
    "invalid": "유효하지 않은 비교 링크입니다. 상품을 최대 4개 선택하세요.",
    "currency": "통화",
    "refresh": "최신 조건 확인",
    "limit": "최대 4개까지 선택할 수 있습니다."
  },
  "ja": {
    "title": "比較リスト",
    "view": "比較を見る",
    "add": "比較に追加",
    "selected": "比較に追加済み",
    "otherBanks": "他行の同じ種類を比較",
    "share": "リンクをコピー",
    "copied": "コピーしました",
    "copyFailed": "このリンクをコピー",
    "save": "この端末に保存",
    "saved": "この端末に保存済み",
    "openSaved": "保存した比較を開く",
    "deleteSaved": "保存した比較を削除",
    "deleted": "保存した比較を削除しました",
    "local": "削除するまで、この端末だけに保存します。",
    "storageError": "端末に保存できません。リンクをコピーして保管できます。",
    "changed": "条件が変更されました",
    "missing": "現在は掲載されていません",
    "error": "商品を確認できませんでした",
    "loading": "最新条件を確認中…",
    "retry": "再試行",
    "empty": "比較する商品を4件まで選んでください。",
    "browse": "商品を探す",
    "clear": "クリア",
    "remove": "削除",
    "count": "{count}件選択",
    "mixed": "種類または通貨が異なります。個別の条件のみ比較でき、まとめた計算はできません。",
    "conditions": "金利基準・期間が異なるか未確認です。同条件の金利比較・計算はできません。",
    "invalid": "比較リンクが無効です。商品を4件まで選んでください。",
    "currency": "通貨",
    "refresh": "最新条件を確認",
    "limit": "選択できるのは4件までです。"
  }
} as const;
export function comparisonCopy(locale: string) { return COPY[locale === 'ko' || locale === 'ja' ? locale : 'en']; }
